import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: { flexDirection: 'column', backgroundColor: '#ffffff', padding: 40 },
    header: { marginBottom: 30, borderBottomWidth: 2, borderBottomColor: '#f0f0f0', paddingBottom: 10 },
    title: { fontSize: 24, marginBottom: 10, },
    subtitle: { fontSize: 12, color: '#666' },
    section: { margin: 10, padding: 10 },
    row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
    label: { fontSize: 12, color: '#666' },
    value: { fontSize: 12, fontWeight: 'bold' },
    table: { marginTop: 20, borderWidth: 1, borderColor: '#eee' },
    tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', padding: 8 },
    tableCell: { fontSize: 10, flex: 1 },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, color: '#999', textAlign: 'center' }
});

export const CampaignReportPdf = () => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Campaign Performance Report</Text>
                <Text style={styles.subtitle}>Generated by WAS Media Hub • December 8, 2025</Text>
            </View>

            <View style={styles.section}>
                <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 15 }}>Executive Summary</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Total Spend:</Text>
                    <Text style={styles.value}>$245,000.00</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Total Impressions:</Text>
                    <Text style={styles.value}>12,500,000</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Average ROAS:</Text>
                    <Text style={styles.value}>4.2x</Text>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={{ fontSize: 14, fontWeight: 'bold', padding: 10 }}>Channel Breakdown</Text>
                <View style={styles.table}>
                    <View style={[styles.tableRow, { backgroundColor: '#f9f9f9' }]}>
                        <Text style={styles.tableCell}>Channel</Text>
                        <Text style={styles.tableCell}>Spend</Text>
                        <Text style={styles.tableCell}>Impressions</Text>
                        <Text style={styles.tableCell}>Clicks</Text>
                    </View>
                    <View style={styles.tableRow}>
                        <Text style={styles.tableCell}>Instagram</Text>
                        <Text style={styles.tableCell}>$85,000</Text>
                        <Text style={styles.tableCell}>4.2M</Text>
                        <Text style={styles.tableCell}>125k</Text>
                    </View>
                    <View style={styles.tableRow}>
                        <Text style={styles.tableCell}>TikTok</Text>
                        <Text style={styles.tableCell}>$120,000</Text>
                        <Text style={styles.tableCell}>6.8M</Text>
                        <Text style={styles.tableCell}>240k</Text>
                    </View>
                    <View style={styles.tableRow}>
                        <Text style={styles.tableCell}>Facebook</Text>
                        <Text style={styles.tableCell}>$40,000</Text>
                        <Text style={styles.tableCell}>1.5M</Text>
                        <Text style={styles.tableCell}>45k</Text>
                    </View>
                </View>
            </View>

            <Text style={styles.footer}>Confidential • WAS Media Hub • Page 1</Text>
        </Page>
    </Document>
);
