'use client';

import React, { useEffect, useState } from 'react';
import { DashboardAnalyticsView } from '@/components/brands/DashboardAnalyticsView';
import { Loader2, AlertCircle } from 'lucide-react';
import { Card } from '@/components/ui/card';

export default function PublicSharePage({ params }: { params: Promise<{ token: string }> }) {
    const { token } = React.use(params);
    const [data, setData] = useState<any>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        async function fetchData() {
            try {
                const res = await fetch(`/api/share/${token}`);
                if (!res.ok) {
                    const err = await res.json();
                    throw new Error(err.error || 'Failed to fetch dashboard data');
                }
                const result = await res.json();
                setData(result);
            } catch (err: any) {
                setError(err.message);
            } finally {
                setIsLoading(false);
            }
        }
        fetchData();
    }, [token]);

    if (isLoading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-slate-50">
                <div className="flex flex-col items-center gap-4">
                    <Loader2 className="h-8 w-8 animate-spin text-brand-primary" />
                    <p className="text-sm font-bold text-slate-400 uppercase tracking-widest">Loading Intelligence Hub...</p>
                </div>
            </div>
        );
    }

    if (error || !data) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-slate-50 p-6">
                <Card className="max-w-md w-full p-8 text-center space-y-4">
                    <div className="inline-flex items-center justify-center h-16 w-16 rounded-full bg-red-50 text-red-500">
                        <AlertCircle className="h-8 w-8" />
                    </div>
                    <h1 className="text-xl font-black text-slate-900 uppercase tracking-tight">Access Denied</h1>
                    <p className="text-sm text-slate-500 font-medium">{error || 'The share link is invalid or has expired.'}</p>
                </Card>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50">
            {/* Minimal Public Header */}
            <header className="bg-white border-b border-slate-200 py-6 px-4 md:px-8 mb-8">
                <div className="max-w-7xl mx-auto flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        {data.brand.logo_url && (
                            <img src={data.brand.logo_url} alt={data.brand.name} className="h-10 w-auto brightness-0" />
                        )}
                        <h1 className="text-lg font-black text-slate-900 uppercase tracking-tight">
                            {data.brand.name} <span className="text-slate-400 ml-2">// CAMPAIGN HUB</span>
                        </h1>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Live Intelligence</span>
                    </div>
                </div>
            </header>

            <main className="max-w-7xl mx-auto px-4 md:px-8 pb-12">
                <DashboardAnalyticsView
                    brand={data.brand}
                    campaigns={data.campaigns}
                    metrics={data.metrics}
                    creatives={data.creatives}
                    isPublic={true}
                />
            </main>

            <footer className="max-w-7xl mx-auto px-4 md:px-8 py-8 border-t border-slate-200 text-center">
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                    Generated by WAS Media Hub Intelligence Engine
                </p>
            </footer>
        </div>
    );
}
